version: '3'

services:
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www:rw
      - ./var:/var/www/var
    environment:
      DATABASE_URL: "mysql://user:passwd@mysql:3306/lead_generation"
    networks:
      - lead_network

  php-worker-sync:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: on-failure
    volumes:
        - .:/var/www:rw
        - ./var:/var/www/var
    environment:
        DATABASE_URL: "mysql://user:passwd@mysql:3306/lead_generation"
    networks:
        - lead_network
    command: ["php", "bin/console", "messenger:consume", "-vv", "doctrine"]

  php-worker-async:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: on-failure
    volumes:
        - .:/var/www:rw
        - ./var:/var/www/var
    environment:
        DATABASE_URL: "mysql://user:passwd@mysql:3306/lead_generation"
    networks:
        - lead_network
    command: [ "php", "bin/console", "messenger:consume", "-vv", "external-details-update" ]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lead_generation
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - lead_network

volumes:
  mysql_data:

networks:
  lead_network:
    external: true